INSERT INTO ebook_library.genre (name) VALUES ('some genre');
INSERT INTO ebook_library.genre (name) VALUES ('some genre2');
INSERT INTO ebook_library.genre (name) VALUES ('some genre3');
INSERT INTO ebook_library.genre (name) VALUES ('some genre4');
INSERT INTO ebook_library.genre (name) VALUES ('some genre5');
INSERT INTO ebook_library.genre (name) VALUES ('some genre6');
INSERT INTO ebook_library.genre (name) VALUES ('some genre7');
INSERT INTO ebook_library.genre (name) VALUES ('some genre8');
INSERT INTO ebook_library.genre (name) VALUES ('some genre9');